import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Mono} from 'next/font/google'
import Navbar from './components/Navbar'

const space = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Seeker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" className="">
      <body className={space.className}>
      <div className="grid min-h-screen place-content-center bg-blue-50 px-4 dark:bg-blue-950">
          <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
